import { intentEmitter } from "@/src/lib/intentEmitter";
import type { StoredIntent } from "@/src/lib/intentEngine";

// Never cache SSE responses
export const dynamic = "force-dynamic";

/**
 * GET /api/intents/stream
 *
 * Server-Sent Events feed. Emits a `data:` line for every new intent that
 * is generated by the event worker. The payload is a JSON object shaped as
 * IntentCardData so the SwipeDeck can push it straight into its card list.
 */
export async function GET(request: Request) {
  const encoder = new TextEncoder();

  const stream = new ReadableStream({
    start(controller) {
      function toCard(intent: StoredIntent) {
        return {
          id:              intent.id,
          intent_summary:  intent.intent_summary,
          proposed_action: intent.possible_actions[0] ?? intent.intent_summary,
          confidence:      intent.confidence,
          reasoning:       intent.reasoning,
          source:          intent.source,
        };
      }

      const sendEvent = (intent: StoredIntent) => {
        try {
          controller.enqueue(
            encoder.encode(`data: ${JSON.stringify(toCard(intent))}\n\n`)
          );
        } catch {
          // Client already disconnected — ignore
        }
      };

      intentEmitter.on("new_intent", sendEvent);

      // Heartbeat keeps the connection alive through proxies / load balancers
      const heartbeat = setInterval(() => {
        try {
          controller.enqueue(encoder.encode(": ping\n\n"));
        } catch {
          clearInterval(heartbeat);
          intentEmitter.off("new_intent", sendEvent);
        }
      }, 20_000);

      // Cleanup when the browser tab closes or component unmounts
      request.signal.addEventListener("abort", () => {
        clearInterval(heartbeat);
        intentEmitter.off("new_intent", sendEvent);
        try { controller.close(); } catch { /* already closed */ }
      });
    },
  });

  return new Response(stream, {
    headers: {
      "Content-Type":    "text/event-stream",
      "Cache-Control":   "no-cache, no-transform",
      "X-Accel-Buffering": "no",
      "Connection":      "keep-alive",
    },
  });
}
